### ISSUE TITLE
Wrong, pollution input

### ISSUE THREAD

**Issue by Technus** [OvermindDL1/bucklescript-testing#1]
https://github.com/OvermindDL1/bucklescript-testing/blob/master/src/main_gtpollute.ml#L38

should be incrementing by number, not setting to a value, we dont have any set pollution mechanics

**Comment by OvermindDL1** [comment]
Ah yes, I had it originally do that but changed it to setting to test how specific values flowed, forgot to set it back, thanks, fixed.  :-)
